name: Build & Deploy Identity Service

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Login to DockerHub
      - name: Login DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 3. Build Docker Image
      - name: Build Image
        run: docker build -t ${{ secrets.DOCKER_IMAGE_NAME_TMS }}:latest .

      # 4. Push Docker Image
      - name: Push Image
        run: docker push ${{ secrets.DOCKER_IMAGE_NAME_TMS }}:latest

      # 5. Deploy to Server
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.FB_HOST }}
          username: ${{ secrets.FB_USER }}
          key: ${{ secrets.FB_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_IMAGE_NAME_TMS }}:latest

            docker rm -f fleetbharat-tms || true

            docker run -d \
              --name fleetbharat-tms \
              --network fleetbharat-net \
              -p 8081:8081 \
              -v /var/www/fleetbharat/uploads:/app/uploads \
              -e ASPNETCORE_ENVIRONMENT=Production \
              -e ASPNETCORE_URLS=http://+:8081 \
              -e ConnectionStrings__Default="${{ secrets.PROD_CONN_FB_TMS }}" \
              --restart always \
              ${{ secrets.DOCKER_IMAGE_NAME_TMS }}:latest
